### ISSUE TITLE
Plain text signatures are not added when replying to a HTML formatted message

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#1086]
Plain text signatures are not added when replying to a HTML formatted message.

A nice feature would be to have the option for both HTML and plain text formatted signatures but it might be more than most people need.

**Comment by rootwork** [comment]
Relatedly, if one sets an HTML-formatted signature and starts a plaintext email, the signature will be inserted with the HTML code. If inserting HTML-formatted signatures in plaintext emails is intentional, Runbox should take the additional step of stripping out the code.

However, I don't think having separate HTML- and plaintext-formatted signatures would be a bad idea -- and would also solve these issues.
