### ISSUE TITLE
Search in the Help portal not returning pages

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1147]
When entering a search term in the help portal (example: https://help.runbox.com/?s=image) the result list is empty. Despite existing pages with the term (example: https://help.runbox.com/runbox-7-webmail-new-features/#Draft_Desk).

**Comment by runboxdave** [comment]
This isn't a Runbox 7 issue so I will close this issue after commenting on it.

We're aware that the help website doesn't return search results for a number of terms, and it seems to be a problem with the WordPress add-on that produces search results. We will look at this as part of our review of the help documentation overall which is due to be done shortly. Thank you.
