### ISSUE TITLE
HTML message sometimes will not load

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#1166]
**Describe the bug**
When opening an HTML message it will sometimes not load the content, and only display "This HTML message has been sanitized for your security.".

Clicking "Original HTML" in the menu does succeed in showing the HTML content in a new tab/window.

**To Reproduce**
1. Go to https://runbox.com/app
2. Click to open an HTML message
3. Observe that the HTML content will sometimes not load

**Expected behavior**
The full HTML message should be displayed.

**Screenshots**
<img width="475" alt="HTML message no content shown" src="https://user-images.githubusercontent.com/1620058/148754812-7da03525-9f4f-4921-9f83-27d72721ca35.png">

**Desktop (please complete the following information):**
 - OS: macOS (appears to affect all)
 - Browser: Safari (appears to affect all)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rootwork** [comment]
I'm also seeing this on Firefox (96.0.3) on Windows 10.

**Comment by castaway** [comment]
I see this a lot in Chrome, where I have HTML off by default (so load the message, see the plain text version, press the HTML checkbox, see empty screen except for .. has been sanitized).

In firefox I've also seen one that somehow interpreted an empty div as an unclosed div (and since that had display:none on it, the whole thing disappeared) - same one was ok in Chrome

**Comment by gtandersen** [comment]
See also #1065.

**Comment by gtandersen** [comment]
The missing content could be due to slow loading of external sources, which could be mitigated with #31.

Another option could be to locally cache such sources with a CDN but this appears more involved.

**Comment by gtandersen** [comment]
Not seen this recently; closing.
