### ISSUE TITLE
Attachments should open in a new tab/window

### ISSUE THREAD

**Issue by kotecky** [runbox/runbox7#1231]
Bug report or a feature request? Attachments that browsers handles open in the same window/tab. When coming back the message being read is gone, the inbox is displayed. (desktop, Win10, latest FF)

To prevent this, attachments should open in a new window/tab. 

Related: https://github.com/runbox/runbox7/pull/1225

**Comment by gtandersen** [comment]
It seems this may have changed recently as attachments used to open in a new tab/window recently. 

@kvviecien could you have a look? :)

**Comment by gtandersen** [comment]
After reviewing recent commits (#1225) we can't find anything that should change this behavior. Download behavior is however a browser setting and it seems Firefox's behavior may have changed to open PDFs directly in Firefox instead of "Always ask".

With the latter setting (on macOS) you are prompted to:

- Open with FIrefox
- Open with [application]
- Save File

Choosing "Open with FIrefox" here will open the file in a new tab/window instead of the same one. It seems Firefox has either changed the default behavior for the "Open in Firefox" setting, or changed the default setting itself.

See this Reddit post for some more context: https://www.reddit.com/r/firefox/comments/tgh8i3/how_to_always_open_pdf_files_in_new_tab_with/

**Comment by kotecky** [comment]
I guess the desired behaviour is that the attachment never uses the thumbnail where the mail app is open. To that goal the attachments should be opened in a new tab, independently of the browser settings. Something like in standard HTML `<a target="blank">` would be. (I will not ask why standard links are not used here :o) )

In Firefox when you want a link to open in a new tab, you hold CTRL while clicking. Today, the app somehow overrules this behaviour and the attachment opens in the same tab ... which is hindering the use of the mail app. 

Another oddity due to the use of something else than an HTML link element is that the context menu (right-click) does not allow to save the attachment using the context-menu item "save link as".

**Comment by gtandersen** [comment]
Agree with this; only clarifying that nothing seems to have changed in the app itself. :)

**Comment by castaway** [comment]
Looking at the current state of the firefox bug I gave above, this seems to now be fixed and will appear in firefox 101 correctly (that is for Runbox7 attachments, where we show pdfs with the "download" attribute, it should prompt to download them (again)). Closing this issue.
