### ISSUE TITLE
Attachment upload progress bar doesn't indicate what it is

### ISSUE THREAD

**Issue by tadzik** [runbox/runbox7#308]
![2019-09-26-131238_1540x144_scrot](https://user-images.githubusercontent.com/86378/65684221-60ad5d00-e05f-11e9-84ea-4d73ebef2a4a.png)

There's nothing here that indicates that an attachment is being uploaded.

**Comment by lauramurinova** [comment]
is it still available?

**Comment by tadzik** [comment]
To pick it up as a task? It sure is – I don't think anyone got to it yet :)

**Comment by lauramurinova** [comment]
Did you mean something like this? (see photo) After the upload is finished it disappears with the progress bar. If you had something else in your mind just tell me, I will change it. If you are satisfied, I can make a PR, so you can review my code.
<img width="1009" alt="Screenshot 2019-10-11 at 14 52 15" src="https://user-images.githubusercontent.com/52161606/66652860-00a9df80-ec37-11e9-9072-b84cf2bdf467.png">

Also I would like to work on the other good first issues, but on mock server I got lots of errors, e.g. after a file upload I couldnt see the attachments. So how can I create an account (cause the sign up page in the production server is not working) so that is better for me to work on them? Thank you.

**Comment by tadzik** [comment]
Hey, this is looking great! Please submit it up for review :)

The mockserver is not a complete thing, it's only just as good as the e2e tests require and not more. The sign up page should definitely be working though. If it's not, please let us know at support@runbox.com or on the [community forum](https://community.runbox.com/).

**Comment by gtandersen** [comment]
@lauramurinova Thanks for your contribution -- looking forward to more in the future!
