### ISSUE TITLE
Validation of recipient addresses

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#39]
Don't allow empty or invalid recipient field input.

Note that pasted addresses don't seem to be submitted. E.g., copy and paste test@runbox.com into a recipient field and send the message. It will bounce with "no recipient address".

**Comment by gtandersen** [comment]
@petersalomonsen @hernan604 Validation of recipient addresses should also occur when a message is sent, to avoid unnecessary bounces. 

(If this is done we may not need to prevent saving drafts with invalid recipients.)

**Comment by davidbowdley** [comment]
Related to this issue:

If you copy and paste an email address (which is what the customer did) or type it manually and you use the mouse to click elsewhere in the compose window the email address remains in the recipient field, but isn't actually "entered", "finalised" whatever you want to call it. In other words, it looks like it's entered but if you know what you are looking for you can tell it isn't because it doesn't have the cross to delete it. With a single recipient you wouldn't necessarily notice though.

The system allows you to click on other fields with the mouse without the email address being entered correctly. Tab works correctly.

**Comment by castaway** [comment]
Reviewing current state (and testing in my browser), it looks like pasted/typed emails are being validated (as of 1c3ac2c), they get checked on "blur". If this is still broken for some we may need browser details.

Latest patch validates the TO (and CC/BCC fields if there is content), on draft/send, and prevents saving/sending if they are invalid. An empty TO field is invalid.
