### ISSUE TITLE
Restructure Account Products

### ISSUE THREAD

**Issue by davidbowdley** [runbox/runbox7#424]
This section also shows expired products that are not "active" (which is useful and desirable) but the title of the section may lead to a misunderstanding.

**Comment by tadzik** [comment]
That'd make a bit confusing since https://runbox.com/app/account/components and its menu item is already called “Account Products”. We could rename it to “Account Components”, since that's how we refer to it in the code.

**Comment by davidbowdley** [comment]
I that case  I would call it "Main Account Products" and move the first section of products that are in "Account add-ons" to this section as they only relate to the Main account in the sense that the Main account holder manages them. I would then change "Account add-ons" to "Sub-accounts".

**Comment by gtandersen** [comment]
The reason it's called **Active products** is that it lists all active/existing products on the main account, whether they are sub-accounts or other add-ons.

**Account add-ons** lists all _available_ products, not just those already subscribed to by the main account.

To make this clearer we could split the page in two sections, first listing existing/current details and then available add-ons.

We could also change "Account upgrades" to "Account plans" or similar since technically you can both up- and downgrade your subscription plan.

So, to hopefully be consistent and better organized we could then end up with:

### Your Products
```
| Your Account Plan | Your Active Products | Your Transactions |
```
### Available Add-ons
```
| Main Account Add-ons | Sub-Account Products |
```

**Comment by davidbowdley** [comment]
"Active products" also lists inactive products which is why I suggested the change.

**Comment by gtandersen** [comment]
@davidbowdley Then we can rename **Your Active Products** to just **Your Products**.

Do we agree on the other proposed changes in my comment?

**Comment by davidbowdley** [comment]
@gtandersen Yes, we could do it that way and it would be a big improvement on what we have now. 

The only further suggestion is to call Your Account Plan something different. My suggestions are Main Account Plan, Your Main Account Plan or Your Main Account. Of all those I would probably choose the last one to retain "Your" and add "Main" and still keep it to three words.

The reason being is that terminology is crucial as we've discussed with other services we offer and if we can hammer home the idea of Main and Sub-accounts it makes it easier for customers to understand what we say elsewhere and when they contact support.

**Comment by gtandersen** [comment]
@davidbowdley In that case I think we should call it **Your Main Account Plan** since it's then consistent with **Your Products** and **Your Transactions** --  and I think it's useful to include "Plan" here because it's a common term used for this type of product.

Perhaps we should also change the title **Your Products** to **Current Products** in the title, and **Available Add-ons** to **Available Products** to be more clear and consistent.

We then get:

### Current Products

`| Your Main Account Plan | Your Products | Your Transactions |`

### Available Products

`| Main Account Add-ons | Sub-Account Products |`

@tadzik If this looks OK to you I can change the HTML, but may need your help with the Angular.

**Comment by davidbowdley** [comment]
Yes, OK, that seems like a big improvement to me and will certainly help with support of the products too.

**Comment by gtandersen** [comment]
@tadzik @davidbowdley This stalled a bit -- do we still agree this is a good idea? :)

**Comment by gtandersen** [comment]
This is completed.
