### ISSUE TITLE
Add setting for Compose format

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#458]
Add a Webmail setting for Compose format (text/HTML) similar to Runbox 6.

Ref: #450

**Comment by tadzik** [comment]
The setting is simple enough, the problem is the UI for it. We're now being a bit inconsistent wrt where we put our settings.

Contacts and Calendar have their own dedicated Settings buttons in the sidebar. There is also the big Settings on the top of the screen which we don't really use for anything context-sensitive: just components that aren't otherwise reachable.

Perhaps the Settings up top should also contain settings related to the currently used app? So if you're in Webmail, Settings would include "Webmail settings" in the dropdown. Or we can just have it mirror the menu itself, which would look somewhat like this:
![2020-03-17-151501_763x380_scrot](https://user-images.githubusercontent.com/86378/76864886-1cf31d80-6862-11ea-944c-83e06017c14c.png)

**Comment by kvviecien** [comment]
So I have couple of suggestions:

- Instead of adding the Compose Format option somewhere in settings, let's just remember the choice the user made. If they uncheck the HTML checkbox, then let's remember that and next time this user is going to compose an email, it's going to be unchecked - "plain text mode" and vice versa - if they check it, then all the emails from now on will be HTML formatted.
That way there is no need to look for it in the settings, it's easy and pretty intuitive.

- How about changing the default format to "plain text"? I don't think people "by default" want to compose HTML messages. In Runbox 6 the default formatting is "plain text" as well.

**Comment by gtandersen** [comment]
Good suggestions @kvviecien, and I agree that UI preferences are better shown where they are used, when possible.
