### ISSUE TITLE
Recurring events in calendar missing and/or off by one day

### ISSUE THREAD

**Issue by cmuszynski** [runbox/runbox7#462]
If I create a recurring event in Thunderbird, the event displays on Runbox 7 one day earlier with the first event missing. 

In Thunderbird, create event occurring at 10pm on **Mon, Wed, Th, Sat** starting on Mon. Feb 17, 2020 ending on Sun Mar 8th, 2020.
Event displays in Thunderbird on Windows as entered. Event displays correctly on aCalendar Android app on my phone as well. Event displays with correct time of day but occurring on Tu, W, Fri, Sun. The event for Monday Feb 17th does not appear. There is no event for Sunday Mar. 8th showing, suggesting that the calendar correctly identified that Sat Mar 7th would be the final occurrence even though Mar 8th was an allowed date when created.

The same issue happens in the exact same way if I create the event in aCal on my phone.

All of my devices and my runbox account are set to the same time zone (Americas/Pacific).

I am unable to test creating a recurring event in Runbox 7 to see how Thunderbird displays it. A regression first seen Feb 12th is preventing the selection of a date/time for calendar events in Runbox 7 in both Firefox and Chrome browsers . Even so, Runbox 7 does not appear to support this level of customization during event creation, which is what lead me to creating the events in Thunderbird instead.

**Comment by tadzik** [comment]
Hi, thanks for your report.

The regression you mentioned about not being able to select a date in events since Feb 12 has been fixed yesterday and is now live: thanks for bringing it up.

For the off-by-one issue, I was unable to reproduce the issue exactly, but I did indeed find some timezone related issues that could have caused what you've described. I have a fix in progress, and I'd appreciate it if you could take a look and see if it fixes your problems (or breaks them differently).

I've put the fix on https://runbox.com/app-beta/. It should show you "Runbox 7 build time: 2020-02-13T11:59:16.000Z" on the main webmail page. In there, the calendar should be handling timezones more correctly than before, which hopefully fixes your issue. Please take a look and tell me if it's any better (or any different).

There is still no option to pick the timezone in the event creator, which is something I'm hoping to address shortly.
