### ISSUE TITLE
Deleting calendar doesn't delete events shown

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#507]
Deleting a calendar in the Calendar section doesn't delete the events until the calendar is manually refreshed (either this or it takes a long time to refresh).

**Comment by tadzik** [comment]
My testing (and [code](https://github.com/runbox/runbox7/blob/master/src/app/calendar-app/calendar.service.ts#L171)) shows otherwise – the events disappeared the moment the calendar was deleted.

What I did: added an event to the calendar, waited for it to show up. Deleted a calendar by the pencil button -> delete this calendar. Observed how the both calendar and the event disappears (from the monthly view).

Is there a way you can reproduce that and write down how to get your result?

**Comment by gtandersen** [comment]
Closing this as it has not been reproduced.
