### ISSUE TITLE
HTML view is sometimes "shorter" than its content, and only grows to desired size after some time

### ISSUE THREAD

**Issue by tadzik** [runbox/runbox7#519]
I noticed that HTML messages sometimes open in a view that only shows a fraction of their size. It happens regardless of the layout (horizontal, vertical, full-height), and regardless of whether the HTML is toggled manually or enabled automatically.

![2020-04-10-122018_835x1049_scrot](https://user-images.githubusercontent.com/86378/78984045-ab875180-7b25-11ea-9839-9da31706e1b5.png)

The HTML view "pops" into its full height after some time has passed: presumably after some time-based updater notices.

Changing the webmail layout while the HTML view is in its correct state (from horizontal to vertical, for example) breaks it again, reseting it to its initial, broken size. Then after a while it fixes itself again.

**Comment by kvviecien** [comment]
The delay adjusting the size occurs because there's a function that's checking height of the html document and applies it to iframe. It takes a second or so to run. It's not really needed though, I believe it can be fully done in CSS.
Now, without the function the problem is iframe itself (it's used to display the html content in emails). No delay is happening anymore but it's a pain to make it responsive. Trying my best!

**Comment by gtandersen** [comment]
Good find @kvviecien -- just keep in mind that the IFRAME is needed for security reasons (separating the HTML content from the app itself).
