### ISSUE TITLE
Reorganize buttons for marking messages read/unread and flagged/unflagged

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#632]
In the message list and in opened messages there is currently one message action button for toggling messages as read/unread, and another for flagged/unflagged.

This is confusing and unreliable, especially when selecting multiple messages with different read and flag status.

A better solution could be to add one button for each of `read`, `unread`, `flagged`, `unflagged`, and gather them as sub-menu items under a main `Message status`  or `Mark as...` button (similar to Runbox 6).

The button could for instance look like this: 
<a href="https://material.io/resources/icons/?search=list&icon=playlist_add_check&style=baseline"><img width="55" alt="Screen Shot 2020-06-08 at 21 02 42" src="https://user-images.githubusercontent.com/1620058/84069969-3cd93f80-a980-11ea-8282-66e22a4362f6.png"></a>

Separate buttons for each of the 4 actions should more clearly indicate which status is being selected and which action is being taken, while not increasing the space consumed by the menu.

Ref #448, #512, #537.

**Comment by castaway** [comment]
Which would  also only toggle the appropriate messages? That is if I select a bunch, some of which are flagged, and some unflagged, and choose "Mark as .. Flagged", we only flip the status of the unflagged ones?

**Comment by kvviecien** [comment]
> Which would also only toggle the appropriate messages? That is if I select a bunch, some of which are flagged, and some unflagged, and choose "Mark as .. Flagged", we only flip the status of the unflagged ones?

I believe that would be the best way to do it. If few messages are selected, then toggle only the ones that have a different status than the one we want them to have. 
So if only read are selected and we want to "Mark as read" - nothing happens. If there are few that are unread, then let's toggle only those.

**Comment by castaway** [comment]
In working on this one I picked some icons from the material icons library - mark_email_unread, mark_email_read, outlined_flag etc.. however the font we are using, from npm material-design-icons , doesn't include these (not updated since 2016!).. in fact google hasn't updated the downloadable font files since then (sigh) .. 

I can get the icons if I link directly to https://fonts.googleapis.com/icon?family=Material+Icons however I don't know if we want to do that.. Otherwise I've found a different module with community fonts - materialdesignicons.com 

@gtandersen opinions? something uptodate would be nice.

**Comment by gtandersen** [comment]
@castaway We shouldn't use externally sourced fonts for privacy reasons.

The community library at http://materialdesignicons.com/ looks extensive with a style identical to that of the original MD library (while using the same icon names), so substituting our current set with this one should be a good idea.

**Comment by castaway** [comment]
Deployed
