### ISSUE TITLE
With index sync on, only 12 messages displayed in Inbox and message counts are wrong

### ISSUE THREAD

**Issue by sinbad** [runbox/runbox7#64]
I have about 25k messages in my inbox. When I first tried R7 they all appeared, but once the index sync was done, I could only see the last 12 messages. If I knew what to search for I could find them, but I couldn't just page through all messages. Also the Search box says "Start typing to search 10493 messages", less than half the actual number.

Disabling the index sync brings the messages back.

**Comment by sinbad** [comment]
I've reproduced this on Firefox 64.0.2 and Chrome 71.0.3578.98, Windows 10.

**Comment by petersalomonsen** [comment]
@sinbad We have identified that sometimes there are some specific email messages crashing the search index build process, which may be the case for you. We are constantly fixing these cases as we see them, but due to privacy there are limitations on what we can see unless users are giving us more direct pointers.

I'm working on a document on how to inspect your search index using Xapian tools - which currently can be found here:

https://github.com/petersalomonsen/runbox7/blob/docs/searchindex/docs/searchindex.md

If you feel like hacking yourself I can improve the docs based on feedback from you on what you need to get to the bottom of the issue. Otherwise you should contact support to get help with your account ( not expose any private info here ).

**Comment by gtandersen** [comment]
@sinbad There appears to have been inconsistencies in the account index and we have reindexed the account from scratch. 

We'll investigate what caused the problem (possibly related to a sizable import), but in the meantime you should now see all the email in your account after stopping and restarting index sync.

**Comment by gtandersen** [comment]
@sinbad We have made several improvements to index synchronization and message counts since the issue was created, so let us know if this problem is still occurring.

**Comment by sinbad** [comment]
Thanks, yes I actually tried R7 only last week again and it's now indexing everything.

**Comment by gtandersen** [comment]
Excellent, thanks!
