### ISSUE TITLE
creation of virtual lists (multiple contacts)

### ISSUE THREAD

**Issue by ghost** [runbox/runbox7#66]
Enigmail(?) has the feature used in some companies and groups, where you have a virtual address (like an entry in /etc/mail/aliases forwarding mail to "A" to ("B","C",...,N)) and you can
associate pairs of users + pubkeys to it.

Without OpenPG this might be useful as well, just for the creation of virtual lists. You might want to address your family, friends, and work contacts in different lists. However members of the lists must be able to exist in more than 1 group and groups could include groups.

**Comment by tadzik** [comment]
This looks to be implemented now as Contact Groups (or Categories, which work very similarly. The compose screen will autocomplete you the groups/categories you have created so that you can email them all at the same time.

Groups cannot include other groups yet, as that potentially has some fun circular properties :) I'll open it as a separate issue.

What do you expect from being able to associate pubkeys with groups?

**Comment by gtandersen** [comment]
This is implemented, while saving public PGP keys has been split out to https://github.com/runbox/runbox7/issues/1462.
