### ISSUE TITLE
Calendar event invitations are sent with the address in local%domain format rather than using @

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#710]
Could possibly be resolved alongside https://github.com/runbox/runbox7/issues/361

The result is that a recipient can't acknowledge a meeting invitation because the senders email address is invalid.

**Comment by tadzik** [comment]
This isn't really a runbox7 issue, but email addresses in caldav have now been fixed for all existing accounts – can you verify that the situation has improved?

**Comment by castaway** [comment]
Patched: See internal PRs for Sabre and Runbox on gitlab

**Comment by castaway** [comment]
Tested this the other day, invitations arrive from "calendar@runbox.com" with reply-to set to the user's address. Fixing the from address is in issue #361

**Comment by MPE2016** [comment]
Hi there:),

I know that 1) this issue is closed and 2) this isn't a real runbox 7 issue, but still:

Calendar invitations are not working right now. It's proven to be hard to get runbox to respond to several requests for this. Is there any way for anyone in the runbox team to do something about it?

All the best,

MPE

**Comment by runboxdave** [comment]
As mentioned above this issue is really now part of https://github.com/runbox/runbox7/issues/361 and is still open. I'll mention it to the team again to see if there is an easy fix.
