### ISSUE TITLE
Menu for replying, forwarding etc... does not always appear.

### ISSUE THREAD

**Issue by runboxdave** [runbox/runbox7#783]
The menu for replying to a message does not always appear when a message is viewed. We need to gather more information on this but in the example I have seen the message appears to be full height.

**Comment by castaway** [comment]
Immediate thoughts - I thought it might be the morebuttonindex calculation being screwey.. but that isnt used for the print/change orientation buttons .. the entire menu is gone in the screenshot. that menu toolbar is display:flex, maybe it got flexed away somehow? Knowing the OS / browser version, as well as whether it happens in not-full-height mode would be useful.

**Comment by castaway** [comment]
After some back+forth with customer(s) (via Dave) the issue seems to be with the "full height" mail pane setting. Making the browser window "full screen", using a private window, or deleting the application storage seems to fix the issue.

We store the pane height as an absolute pixel size (not a percentage), so likely some (firefox?) browsers set that, and then push the menu off the top of the view, if it doesn't fit. For example if the customer had a large browser window, set the view to full height, then made their window smaller.

**Comment by castaway** [comment]
It doesn't look like there's a particular reason we're storing an absolute value instead of a percentage, so I'll try swapping it over

**Comment by gtandersen** [comment]
This is still occurring for some users, and we will try to gather more details from them but is there anything obvious we could look for in the code in the meantime?

**Comment by castaway** [comment]
From @davidbowdley 's new report it seems that even full-screening the browser doesn't help now, so this could be something different (or I messed up). The fix was largely a guess unfortunately, as we couldn't reproduce it locally. 

The next thing I can think of is to rejig the interface so that the menu never quite goes away - maybe in full height pane mode it could reduce to a sliver - and pop down when the mouse is moved to the top edge of the screen?

**Comment by castaway** [comment]
Hmm, realised its not actually supposed to go away, maybe we need to change the styling so that it has a fixed height? It would be handy to try and reproduce this locally, since it doesn't seem to be all browsers.
