### ISSUE TITLE
Make Add-ons cards mobile friendly

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#826]
Add-ons cards are too wide and don't scale down on mobile screens.

See: https://runbox.com/app/account/addons

**Comment by tadzik** [comment]
Fixed in 0d9005d as part of #808, along with the overlapping text in subscription special offers. This slightly alters the addons card layout on both desktop on mobile, but I think it turns out better for it:

![addons-desktop](https://user-images.githubusercontent.com/86378/103374022-c300d300-4ad6-11eb-9364-9398cdc89805.png)

![addons](https://user-images.githubusercontent.com/86378/103373977-a49ad780-4ad6-11eb-8691-db035249e2c5.png)
