### ISSUE TITLE
Make payment forms mobile friendly.

### ISSUE THREAD

**Issue by gtandersen** [runbox/runbox7#831]
The payment form(s) don't fit on mobile screens.

**Comment by tadzik** [comment]
Improved it somewhat in 9fe8862971a4989924030b691a853970a7790944 (as part of https://github.com/runbox/runbox7/pull/808), but I'm not totally happy with the result, and I've run out of ideas to improve it further.

On desktop we end up with this (zipcode taking up more space than the other two fields):
![stripe-desktop](https://user-images.githubusercontent.com/86378/103411376-e592fa80-4b6f-11eb-9925-34bd84e9e331.png)

While on mobile we have this (zipcode becoming worthy of its own row, while expiration date struggles for space):
![stripe-mobile](https://user-images.githubusercontent.com/86378/103411398-078c7d00-4b70-11eb-86c6-762e075ce203.png)

It's at least usable on mobile, so that's a step forward, but could look a little better. Wanna give it a go, @kvviecien?

**Comment by kvviecien** [comment]
<img src="https://i.imgur.com/p0iBbbs.png">
