### ISSUE TITLE
Index corruption

### ISSUE THREAD

**Issue by RolandRBX** [runbox/runbox7#97]
Browser: Firefox on Windows
Scenario:
1. Open a tab and login to your MAIN account in RB 7 (index previously activated)
2. Open another tab and login to your SUB account in RB 6
3. Go to the RB 7 tab
4. Some messages from you sub account are listed in your main account! When trying to read one of them you get "{"status":"error","errors":["message_could_not_be_found"]}"
5. Some messages from your main account begin to vanish! The number displayed in the search box decreases.
6. Open another tab and login to your main account in RB 6: messages are properly displayed (phew!)
7. Removing the index solves the issue
All this means there's no isolation between accounts.
Leading to potential steal of data by malicious people.

**Comment by petersalomonsen** [comment]
Session cookies are used to identify the logged in user, so the same session cookie applies to all tabs, meaning you can only be logged into one account at the time in one browser. Logging into different accounts simultaneously will cause confusion as you experience. With RB7 sync active, the message search index is stored locally and if it receives messages from the other account, that will corrupt the index. However this is only locally and not on the server, so removing and downloading the index again will fix it. It does not cause leak of data between accounts as you suggest.

I would suggest a feature request of either detect login of other accounts in other tabs/windows which will automatic log out the previous account, or a change from using cookies to session storage (which is only per tab/window). The latter is a bit more change.

**Comment by kservik** [comment]
Hello RolandRBX, 

Logging RMM6 or Runbox 7, authenticates you for both. You are logged into the last account you logged into.

This can be solved by using different web browsers for each account. You can use Firefox, Chrome, Vivaldi and Brave and you can be logged into 4 different accounts at the same time. 

Firefox also got several plugins like "Firefox Multi-Account Containers" that lets you be logged into many accounts in the same web browser: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

It is highly recommended if you often log into more than one account and it is also great for separation private browsing and browsing on sites with ad trackers and such.

**Comment by RolandRBX** [comment]
Yes the user can avoid the issue.
But the software must prevent the issue.
Corruption is not a good thing...

**Comment by petersalomonsen** [comment]
Absolutely not a good thing to get the index corrupted, so I think the first fix would be to automatically detect if you log into another user in another tab/window, and close Runbox7 if that happens. Currently Runbox 7 will go to the login-screen if you logout from another tab, but not if you log into another account.

**Comment by RolandRBX** [comment]
Shouldn't this issue labelled as "bug" ? At least.

**Comment by hernan604** [comment]
@RolandRBX that is not a bug. That is how browsers handle the user session per domain. RMM6 and RMM7 are on the same domain in different urls. Your browser understands you are logged in runbox.com domain, and does not care if you open runbox.com/mail or runbox.com/app.

If you use firefox, you can install the firefox "Multi Account Container" extension: 

https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

This extension allows the user to create multiple containers which separate browser sessions per tab. That way the user is able to create a container called "Main email" and another "Aliases email" and use those 2 to create 2 tabs that logs with different user session.

If you dont install such extension, you will need to open 2 different browsers, or open one tab in normal mode and another in incognito mode. But i really recommend you use multi account container specially since its an extension from mozilla, the creator of firefox.

**Comment by gtandersen** [comment]
This should be resolved and can't reproduce the problem, as attempting to access the login screen in Runbox 6 while having an existing session in another tab will automatically log you into the same account.
